In [33]:
import pandas as pd

In [34]:
cr2 = pd.read_excel('carrfour sales.xlsx')

In [35]:
cr2

,TransactionID,OrderDate,OrderTime,StoreID,StoreName,StoreCity,StoreRegion,StoreType,CustomerID,CustomerName,Gender,Age,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,DiscountValue,PaymentMethod,OrderChannel,OrderStatus,ReturnFlag
0,TRX100000,12-07-2024,18:22,S04,Carrefour Nasr City,Alexandria,North Coast,Online Hub,C1164,mona hassan,F,40,P226,Fresh Fan,electronics,Samsung,4,18861,500.0,Card,Website,Cancelled,Yes
1,TRX100001,2023-10-21,8:56,S13,Carrefour Nasr City,Alexandria,North Coast,Hyper,C1414,Ahmed Ali,Female,56,P201,Apple iPhone,electronics,LG,1,EGP 21833,0.0,Wallet,Website,Cancelled,No
2,TRX100002,17-04-2024,23:53,S05,carrefour giza,Giza,Delta,Express,C1397,Ahmed Ali,Female,26,P225,Fresh Fan,Elec,LG,1,10628,500.0,Card,Store,Returned,Yes
3,TRX100003,05/04/2024,15:58,S11,CARREFOUR Maadi,Cairo,Delta,Hyper,C1258,sara Mahmoud,Male,39,P231,Apple iPhone,electronics,Fresh,2,17871,200.0,Wallet,Store,Completed,No
4,TRX100004,2024-10-16,17:00,S11,carrefour giza,Alexandria,Greater Cairo,Hyper,C1164,KARIM Adel,F,51,P230,Apple iPhone,electronics,HP,5,EGP 23273,15.0,Card,App,Cancelled,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,TRX101195,27-02-2023,11:49,S08,Carrefour Nasr City,Cairo,Greater Cairo,Express,C1322,sara Mahmoud,F,36,P251,Fresh Fan,Electronics,HP,3,EGP 24665,15.0,Cash,App,Cancelled,Yes
1196,TRX101196,09-08-2023,17:15,S14,carrefour giza,Giza,North Coast,Hyper,C1362,mona hassan,F,34,P213,Samsung TV,ELC,LG,5,8919,15.0,Card,App,completed,Yes
1197,TRX101197,06-08-2023,11:38,S08,Carrefour Nasr City,Giza,Delta,Hyper,C1335,mona hassan,F,18,P258,HP Laptop,ELC,Fresh,1,10086,500.0,Card,Website,completed,Yes
1198,TRX101198,09/09/2024,15:02,S07,CARREFOUR Maadi,Giza,Delta,Hyper,C1220,KARIM Adel,Female,63,P211,HP Laptop,ELC,HP,1,24206,NaN,Card,Website,Returned,Yes
1199,TRX101199,2022-02-23,16:20,S12,Carrefour-Alex,Alexandria,Delta,Online Hub,C1309,sara Mahmoud,F,32,P201,Samsung TV,Elec,LG,1,1059,5.0,Cash,App,Returned,No

In [36]:
cr=cr2.copy()

In [37]:
cr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionID  1200 non-null   object
 1   OrderDate      1200 non-null   object
 2   OrderTime      1200 non-null   object
 3   StoreID        1200 non-null   object
 4   StoreName      1200 non-null   object
 5   StoreCity      1200 non-null   object
 6   StoreRegion    1200 non-null   object
 7   StoreType      1200 non-null   object
 8   CustomerID     1200 non-null   object
 9   CustomerName   1200 non-null   object
 10  Gender         1200 non-null   object
 11  Age            1200 non-null   int64
 12  ProductID      1200 non-null   object
 13  ProductName    1200 non-null   object
 14  Category       1200 non-null   object
 15  Brand          1200 non-null   object
 16  Quantity       1200 non-null   int64
 17  UnitPrice      1200 non-null   object
 18  DiscountValue  1031 non-null   float64
 19  PaymentMethod  1200 non-null   object
 20  OrderChannel   1200 non-null   object
 21  OrderStatus    1200 non-null   object
 22  ReturnFlag     1200 non-null   object
dtypes: float64(1), int64(2), object(20)
memory usage: 215.8+ KB

In [38]:
pd.set_option('display.max_columns', None)

In [39]:
cr.duplicated().sum()

np.int64(0)

In [40]:
cr[cr['TransactionID'].duplicated()]

Empty DataFrame
Columns: [TransactionID, OrderDate, OrderTime, StoreID, StoreName, StoreCity, StoreRegion, StoreType, CustomerID, CustomerName, Gender, Age, ProductID, ProductName, Category, Brand, Quantity, UnitPrice, DiscountValue, PaymentMethod, OrderChannel, OrderStatus, ReturnFlag]
Index: []

In [41]:
cr.isnull().sum()

TransactionID      0
OrderDate          0
OrderTime          0
StoreID            0
StoreName          0
StoreCity          0
StoreRegion        0
StoreType          0
CustomerID         0
CustomerName       0
Gender             0
Age                0
ProductID          0
ProductName        0
Category           0
Brand              0
Quantity           0
UnitPrice          0
DiscountValue    169
PaymentMethod      0
OrderChannel       0
OrderStatus        0
ReturnFlag         0
dtype: int64

In [42]:
cr['OrderDate'] = pd.to_datetime(cr['OrderDate'], format='mixed')

In [43]:
cr['month']=cr['OrderDate'].dt.month
cr['month name']=cr['OrderDate'].dt.month_name()
cr['year']=cr['OrderDate'].dt.year
cr['day']=cr['OrderDate'].dt.day

In [44]:
cr['StoreName']=cr['StoreName'].str.title()

In [45]:
cr['StoreName']=cr['StoreName'].str.strip()

In [46]:
cr['CustomerName']=cr['CustomerName'].str.title()

In [47]:
cr['CustomerName']=cr['CustomerName'].str.strip()

In [48]:
cr['Category'].value_counts()

Category
Elec           318
ELC            310
electronics    301
Electronics    271
Name: count, dtype: int64

In [49]:
cr['Category']=cr['Category'].str.replace('Elec','Electronics')

In [50]:
cr['Category']=cr['Category'].str.replace('ELC','Electronics')

In [51]:
cr['Category']=cr['Category'].str.replace('Electronicstronics','Electronics')

In [52]:
cr['Category']=cr['Category'].str.replace('electronics','Electronics')

In [53]:
cr['UnitPrice'] = (
    cr['UnitPrice']
    .astype(str)
    .str.replace(r'[^0-9.]', '', regex=True))

In [54]:
cr['UnitPrice'] = pd.to_numeric(cr['UnitPrice'], errors='coerce')

In [55]:
cr['DiscountValue'].isnull().sum()

np.int64(169)

In [56]:
cr['DiscountValue'].median()

15.0

In [57]:
cr['DiscountValue'] = cr['DiscountValue'].fillna(
    cr['DiscountValue'].median())

In [58]:
cr['OrderStatus']=cr['OrderStatus'].str.title()

In [59]:
cr['Gender']=cr['Gender'].replace('M','Male')
cr['Gender']=cr['Gender'].replace('F','Female')

In [60]:
cr

,TransactionID,OrderDate,OrderTime,StoreID,StoreName,StoreCity,StoreRegion,StoreType,CustomerID,CustomerName,Gender,Age,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,DiscountValue,PaymentMethod,OrderChannel,OrderStatus,ReturnFlag,month,month name,year,day
0,TRX100000,2024-12-07,18:22,S04,Carrefour Nasr City,Alexandria,North Coast,Online Hub,C1164,Mona Hassan,Female,40,P226,Fresh Fan,Electronics,Samsung,4,18861,500.0,Card,Website,Cancelled,Yes,12,December,2024,7
1,TRX100001,2023-10-21,8:56,S13,Carrefour Nasr City,Alexandria,North Coast,Hyper,C1414,Ahmed Ali,Female,56,P201,Apple iPhone,Electronics,LG,1,21833,0.0,Wallet,Website,Cancelled,No,10,October,2023,21
2,TRX100002,2024-04-17,23:53,S05,Carrefour Giza,Giza,Delta,Express,C1397,Ahmed Ali,Female,26,P225,Fresh Fan,Electronics,LG,1,10628,500.0,Card,Store,Returned,Yes,4,April,2024,17
3,TRX100003,2024-05-04,15:58,S11,Carrefour Maadi,Cairo,Delta,Hyper,C1258,Sara Mahmoud,Male,39,P231,Apple iPhone,Electronics,Fresh,2,17871,200.0,Wallet,Store,Completed,No,5,May,2024,4
4,TRX100004,2024-10-16,17:00,S11,Carrefour Giza,Alexandria,Greater Cairo,Hyper,C1164,Karim Adel,Female,51,P230,Apple iPhone,Electronics,HP,5,23273,15.0,Card,App,Cancelled,No,10,October,2024,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,TRX101195,2023-02-27,11:49,S08,Carrefour Nasr City,Cairo,Greater Cairo,Express,C1322,Sara Mahmoud,Female,36,P251,Fresh Fan,Electronics,HP,3,24665,15.0,Cash,App,Cancelled,Yes,2,February,2023,27
1196,TRX101196,2023-09-08,17:15,S14,Carrefour Giza,Giza,North Coast,Hyper,C1362,Mona Hassan,Female,34,P213,Samsung TV,Electronics,LG,5,8919,15.0,Card,App,Completed,Yes,9,September,2023,8
1197,TRX101197,2023-06-08,11:38,S08,Carrefour Nasr City,Giza,Delta,Hyper,C1335,Mona Hassan,Female,18,P258,HP Laptop,Electronics,Fresh,1,10086,500.0,Card,Website,Completed,Yes,6,June,2023,8
1198,TRX101198,2024-09-09,15:02,S07,Carrefour Maadi,Giza,Delta,Hyper,C1220,Karim Adel,Female,63,P211,HP Laptop,Electronics,HP,1,24206,15.0,Card,Website,Returned,Yes,9,September,2024,9
1199,TRX101199,2022-02-23,16:20,S12,Carrefour-Alex,Alexandria,Delta,Online Hub,C1309,Sara Mahmoud,Female,32,P201,Samsung TV,Electronics,LG,1,1059,5.0,Cash,App,Returned,No,2,February,2022,23

In [61]:
cr.to_excel('cleaned_data.xlsx', index=False)

In [62]:
cr.to_csv('cleaned_data.csv', index=False)